package com.example.core;

import io.vertx.core.buffer.Buffer;
import io.vertx.core.eventbus.MessageCodec;
import io.vertx.core.json.JsonObject;

//TODO: this was autogenerated by chat - verify
public class EventMessageCodec implements MessageCodec<Event, Event> {

    @Override
    public void encodeToWire(Buffer buffer, Event event) {
        String json = JsonObject.mapFrom(event).encode();
        byte[] bytes = json.getBytes();
        buffer.appendInt(bytes.length);
        buffer.appendBytes(bytes);
    }

    @Override
    public Event decodeFromWire(int pos, Buffer buffer) {
        int length = buffer.getInt(pos);
        pos += 4;
        byte[] bytes = buffer.getBytes(pos, pos + length);
        String json = new String(bytes);
        return new JsonObject(json).mapTo(Event.class);
    }

    @Override
    public Event transform(Event event) {
        // dla local event bus: po prostu zwracamy referencję
        return event;
    }

    @Override
    public String name() {
        return "eventCodec";
    }

    @Override
    public byte systemCodecID() {
        return -1; // -1 oznacza, że to custom codec
    }
}
